### PR TITLE
fix all %20 email errors

### PR DESCRIPTION
**Pull request by anonymousaga**
I do the same fix from studentemails.php to all other instances of `mailto: `

### CODE REVIEW

**Comment by wolfe3d** [comment]
You do or did the same.  Grammar check back at you.

**Review by wolfe3d — APPROVED** [review]
Nice change applied consistently.

**Comment by anonymousaga** [comment]
Thanks!

**Comment by anonymousaga** [comment]
> You do or did the same. Grammar check back at you.

🙃

**Pull request merged**
