### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by chinmay314**
I have added the form to add a new tournament, add tournamentadd.php, and modified the appropriate function in data.js. I guessed on which fields should be required and which should send default values if no value is sent. Let me know which of these needs to be changed.

Also, should we change tournament type to a string rather than an int? I don't know if 1/2/3 make sense to the end user as tournament types. Should they instead be Full/Mini/Hybrid?

### CODE REVIEW

**Comment by wolfe3d** [comment]
For tournament type – you need to make this a drop down that displays types as strings to the user, but it is actually stored in the database as an integer.  Using int rather than a string, saves space in the database and decreases the chance of database corruption.  In fact, it is best to create a table that stores the strings just like phonetype does.

Why are there so many changes to styles.css?  I looked at the file an I don’t see any real mods.

Doug Wolfe
Build Your Own Jeopardy

From: Chinmay J
Sent: Sunday, June 6, 2021 2:59 PM
To: wolfe3d/sodata
Cc: Subscribed
Subject: [wolfe3d/sodata] Feature (#14)

I have added the form to add a new tournament, add tournamentadd.php, and modified the appropriate function in data.js. I guessed on which fields should be required and which should send default values if no value is sent. Let me know which of these needs to be changed.
Also, should we change tournament type to a string rather than an int? I don't know if 1/2/3 make sense to the end user as tournament types. Should they instead be Full/Mini/Hybrid?

You can view, comment on, or merge this pull request online at:
  https://github.com/wolfe3d/sodata/pull/14
Commit Summary
• incomplete work on adding a new tournament
• Merge branch 'main' into feature
• progress
• tournament add core functionality
• Merge branch 'feature' of https://github.com/wolfe3d/sodata into feature
File Changes
• M css/style.css (2101) 
• M data.js (70) 
• M students.php (1) 
• A tournamentadd.php (55) 
• M tournamentedit.php (20) 
• M tournaments.php (96) 
• M tournamentslist.php (2) 
• M tournamentview.php (1) 
Patch Links:
• https://github.com/wolfe3d/sodata/pull/14.patch
• https://github.com/wolfe3d/sodata/pull/14.diff

**Comment by chinmay314** [comment]
I made the drop down exactly as you are describing it for add, but not for
the tournament edit. Also, I think a vscode extension I have autoformatted
styles.css when I made a small edit. That edit made the error messages red
for when the user doesn't enter the tournament name, host, or dates.
Earlier it was gray.

**Comment by wolfe3d** [comment]
Great.  Make the drop down for edit too.On Jun 6, 2021 4:46 PM, Chinmay J ***@***.***> wrote:

I made the drop down exactly as you are describing it for add, but not for

the tournament edit. Also, I think a vscode extension I have autoformatted

styles.css when I made a small edit. That edit made the error messages red

for when the user doesn't enter the tournament name, host, or dates.

Earlier it was gray.

**Comment by chinmay314** [comment]
Done. Ready to merge when you are.

Also, are you on vacation currently? If so, I'm sorry to bother you about this, and I won't add further comments, just pull reqs for you to see when you get back.

**Comment by wolfe3d** [comment]
You can do more work and let me know.  I may have time to do intermittent work on this.  If you have time tackle, some of the TODOs.

**Pull request merged**
